### ISSUE TITLE
'null' values are not allowed in templates

### ISSUE THREAD

**Issue by meteabogdan** [davidgf/serverless-plugin-canary-deployments#38]
Hi, not sure if this is a bug or I'm not doing it properly but every time I try to deploy using the plugin i get the following:

`after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: The CloudFormation template is invalid: [/Resources/GetDashtickerDashdropdownsLambdaFunctionAliasLive/Type/FunctionVersion/Fn::GetAtt/0] 'null' values are not allowed in templates
    at provider.request.catch (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:25:13)
From previous event:
    at AwsDeploy.validateTemplate (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:121:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:117:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:43:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.12.0
     Serverless Version:     1.32.0
 
Exited with code 1`

The deployment settings for my function are:
`deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live`

Would anyone know why? Thanks

**Comment by davidgf** [comment]
Hey @meteabogdan, could I have a look at the CloudFormation template generated by Serverless and the `serverless.yml` file?

**Comment by meteabogdan** [comment]
Hi @davidgf, 
I found the problem. 
The versionFunctions serverless parameter was set to false because we ran out of lambda storage and we weren't really rolling back using the versions anyway.
So, if anyone else runs into this problem, it could be that function versioning is off. Turning it back on would fix it.
Thank you for your time! And thanks for the plugin!

**Comment by asaf-kali** [comment]
For anyone who gets here in the future, under `provider` section, remove this line (the default value is `true`):
<img width="220" alt="image" src="https://github.com/davidgf/serverless-plugin-canary-deployments/assets/28392088/dc8dfa79-98e0-46ff-a104-a7c36869ab20">
